
services:
# connect to db container: 
#     docker exec -it psdb bash
#     bash: mysql --password="example"
# psql connection string in Go: 
#     postgres://root:secret@localhost:5432/testdb?sslmode=disable

  psdb:
    container_name: psdb
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports: 
      - "5432:5432"
    volumes:
      - psql_data:/var/lib/postgresql/data

#  adminer:
#    image: adminer
#    container_name: adminer-container
#    restart: always
#    ports: 
#      - 8080:8080

volumes:
  psql_data: